package com.mrcrayfish.guns.datagen;

import com.mrcrayfish.guns.Reference;
import com.mrcrayfish.guns.common.GripType;
import com.mrcrayfish.guns.common.Gun;
import com.mrcrayfish.guns.init.ModItems;
import com.mrcrayfish.guns.init.ModSounds;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;

import java.util.concurrent.CompletableFuture;

/**
 * Author: MrCrayfish
 */
public class GunGen extends GunProvider
{
    public GunGen(PackOutput output, CompletableFuture<HolderLookup.Provider> registries)
    {
        super(output, registries);
    }

    @Override
    protected void registerGuns()
    {
        this.addGun(new ResourceLocation(Reference.MOD_ID, "pistol"), Gun.Builder.create()
                .setFireRate(4)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(12)
                .setReloadAmount(12)
                .setRecoilAngle(4.0F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.P9.get())
                .setDamage(6.0F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_PISTOL_FIRE.get())
                .setReloadSound(ModSounds.ITEM_PISTOL_RELOAD.get())
                .setCockSound(ModSounds.ITEM_PISTOL_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_PISTOL_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_PISTOL_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.3, 2.64)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 4.5, -1.0))
                .setScope(0.75F, 0.0, 3.7, 6.0)
                .setBarrel(0.5F, 0.0, 3.3, 2.65)
                .setStock(1.0F, 0.0, 3.3, 7.95)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "pitol_auto"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(2)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(20)
                .setReloadAmount(20)
                .setRecoilAngle(4.0F)
                .setRecoilKick(0.25F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(6.0F)
                .setAmmo(ModItems.P9.get())
                .setDamage(4.5F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(20)
                .setFireSound(ModSounds.ITEM_PISTOL_AUTO_FIRE.get())
                .setReloadSound(ModSounds.ITEM_PISTOL_AUTO_RELOAD.get())
                .setCockSound(ModSounds.ITEM_PISTOL_AUTO_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_PISTOL_AUTO_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_PISTOL_AUTO_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.35, 0.0, 3.5, 1.79)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.8F)
                        .setOffset(0.0, 4.8, -1.0))
                .setScope(1.0F, 0.0, 4.0, 5.5)
                .setBarrel(0.5F, 0.0, 3.2, 2.2)
                .setStock(1.0F, 0.0,3.2, 8.2)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "pitol_survival"), Gun.Builder.create()
                .setFireRate(2)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(1)
                .setReloadAmount(1)
                .setRecoilAngle(4.0F)
                .setRecoilKick(0.25F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(6.0F)
                .setAmmo(ModItems.P9.get())
                .setDamage(7.5F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(20)
                .setFireSound(ModSounds.ITEM_PISTOL_SURVIVAL_FIRE.get())
                .setReloadSound(ModSounds.ITEM_PISTOL_SURVIVAL_RELOAD.get())
                .setCockSound(ModSounds.ITEM_PISTOL_SURVIVAL_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_PISTOL_SURVIVAL_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_PISTOL_SURVIVAL_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.35, 0.0, 3.5, 1.79)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.8F)
                        .setOffset(0.0, 4.8, -1.0))
                .setScope(1.0F, 0.0, 4.0, 5.5)
                .setBarrel(0.5F, 0.0, 3.2, 2.2)
                .setStock(1.0F, 0.0,3.2, 8.2)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "pistol_tti"), Gun.Builder.create()
                .setFireRate(3)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(14)
                .setReloadAmount(14)
                .setRecoilAngle(4.0F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.P9.get())
                .setDamage(6.5F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_PISTOL_TTI_FIRE.get())
                .setReloadSound(ModSounds.ITEM_PISTOL_TTI_RELOAD.get())
                .setCockSound(ModSounds.ITEM_PISTOL_TTI_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_PISTOL_TTI_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_PISTOL_TTI_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.3, 2.64)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 4.5, -1.0))
                .setBarrel(0.5F, 0.0, 3.3, 2.65)
                .setStock(1.0F, 0.0, 3.3, 7.95)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "pistol_sar"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(2)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(6)
                .setReloadAmount(1)
                .setRecoilAngle(7.0F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.P45.get())
                .setDamage(6.5F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_PISTOL_SAR_FIRE.get())
                .setReloadSound(ModSounds.ITEM_PISTOL_SAR_RELOAD.get())
                .setCockSound(ModSounds.ITEM_PISTOL_SAR_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_PISTOL_SAR_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_PISTOL_SAR_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.3, 2.64)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 4.5, -1.0))
                .setBarrel(0.5F, 0.0, 3.3, 2.65)
                .setStock(1.0F, 0.0, 3.3, 7.95)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "pistol_dar"), Gun.Builder.create()
                .setFireRate(5)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(6)
                .setReloadAmount(1)
                .setRecoilAngle(7.0F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.P45.get())
                .setDamage(6.5F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_PISTOL_DAR_FIRE.get())
                .setReloadSound(ModSounds.ITEM_PISTOL_DAR_RELOAD.get())
                .setCockSound(ModSounds.ITEM_PISTOL_DAR_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_PISTOL_DAR_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_PISTOL_DAR_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.3, 2.64)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 4.5, -1.0))
                .setBarrel(0.5F, 0.0, 3.3, 2.65)
                .setStock(1.0F, 0.0, 3.3, 7.95)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "rifle_assault"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(3)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(25)
                .setReloadAmount(5)
                .setRecoilKick(0.25F)
                .setRecoilAngle(3.0F)
                .setSpread(4.0F)
                .setAmmo(ModItems.R556.get())
                .setDamage(6.5F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10F)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_RIFLE_ASSAULT_FIRE.get())
                .setReloadSound(ModSounds.ITEM_RIFLE_ASSAULT_RELOAD.get())
                .setCockSound(ModSounds.ITEM_RIFLE_ASSAULT_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_RIFLE_ASSAULT_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_RIFLE_ASSAULT_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6, -6.41)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 5.2, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6, -5.9)
                .setStock(1.0F, 0.0, 3.6, 8.2)
                .setUnderBarrel(1.0F, 0.0, 2.799, -1.0)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "rifle_assault_ziptie"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(3)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(30)
                .setReloadAmount(10)
                .setRecoilKick(0.25F)
                .setRecoilAngle(3.0F)
                .setSpread(4.0F)
                .setAmmo(ModItems.R556.get())
                .setDamage(6.5F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10F)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_RIFLE_ASSAULT_ZIPTIE_FIRE.get())
                .setReloadSound(ModSounds.ITEM_RIFLE_ASSAULT_ZIPTIE_RELOAD.get())
                .setCockSound(ModSounds.ITEM_RIFLE_ASSAULT_ZIPTIE_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_RIFLE_ASSAULT_ZIPTIE_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_RIFLE_ASSAULT_ZIPTIE_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6, -6.41)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 5.2, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6, -5.9)
                .setStock(1.0F, 0.0, 3.6, 8.2)
                .setUnderBarrel(1.0F, 0.0, 2.799, -1.0)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "rifle_tactical"), Gun.Builder.create()
                .setFireRate(8)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(10)
                .setReloadAmount(2)
                .setRecoilAngle(10.0F)
                .setRecoilKick(0.5F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.R762.get())
                .setDamage(11.0F)
                .setProjectileAffectedByGravity(true)
                .setProjectileSize(0.0625F)
                .setProjectileSpeed(20.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_RIFLE_TACTICAL_FIRE.get())
                .setReloadSound(ModSounds.ITEM_RIFLE_TACTICAL_RELOAD.get())
                .setCockSound(ModSounds.ITEM_RIFLE_TACTICAL_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_RIFLE_TACTICAL_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_RIFLE_TACTICAL_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.8365, -10.21)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 4.6223, 6.0))
                .setScope(1.0F, 0.0, 4.3, 3.3)
                .setBarrel(0.45F, 0.0, 3.8365,-10.2)
                .setStock(1.0F, 0.0, 3.1294, 8.3)
                .setUnderBarrel(1.0F, 0.0, 2.63, -0.5)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "rifle_battle"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(8)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(20)
                .setReloadAmount(10)
                .setRecoilAngle(10.0F)
                .setRecoilKick(0.5F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.R762.get())
                .setDamage(9.0F)
                .setProjectileAffectedByGravity(true)
                .setProjectileSize(0.0625F)
                .setProjectileSpeed(20.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_RIFLE_BATTLE_FIRE.get())
                .setReloadSound(ModSounds.ITEM_RIFLE_BATTLE_RELOAD.get())
                .setCockSound(ModSounds.ITEM_RIFLE_BATTLE_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_RIFLE_BATTLE_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_RIFLE_BATTLE_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.8365, -10.21)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 4.6223, 6.0))
                .setScope(1.0F, 0.0, 4.3, 3.3)
                .setBarrel(0.45F, 0.0, 3.8365,-10.2)
                .setStock(1.0F, 0.0, 3.1294, 8.3)
                .setUnderBarrel(1.0F, 0.0, 2.63, -0.5)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "rifle_battle_soviet"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(5)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(30)
                .setReloadAmount(30)
                .setRecoilAngle(10.0F)
                .setRecoilKick(0.5F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.R762.get())
                .setDamage(10.0F)
                .setProjectileAffectedByGravity(true)
                .setProjectileSize(0.0625F)
                .setProjectileSpeed(20.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_RIFLE_BATTLE_SOVIET_FIRE.get())
                .setReloadSound(ModSounds.ITEM_RIFLE_BATTLE_SOVIET_RELOAD.get())
                .setCockSound(ModSounds.ITEM_RIFLE_BATTLE_SOVIET_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_RIFLE_BATTLE_SOVIET_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_RIFLE_BATTLE_SOVIET_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.8365, -10.21)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 4.6223, 6.0))
                .setScope(1.0F, 0.0, 4.3, 3.3)
                .setBarrel(0.45F, 0.0, 3.8365,-10.2)
                .setStock(1.0F, 0.0, 3.1294, 8.3)
                .setUnderBarrel(1.0F, 0.0, 2.63, -0.5)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "rifle_scout"), Gun.Builder.create()
                .setFireRate(30)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(5)
                .setReloadAmount(1)
                .setRecoilAngle(10.0F)
                .setRecoilKick(0.5F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.R762.get())
                .setDamage(13.0F)
                .setProjectileAffectedByGravity(true)
                .setProjectileSize(0.0625F)
                .setProjectileSpeed(20.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_RIFLE_SCOUT_FIRE.get())
                .setReloadSound(ModSounds.ITEM_RIFLE_SCOUT_RELOAD.get())
                .setCockSound(ModSounds.ITEM_RIFLE_SCOUT_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_RIFLE_SCOUT_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_RIFLE_SCOUT_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.8365, -10.21)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 4.6223, 6.0))
                .setScope(1.0F, 0.0, 4.3, 3.3)
                .setBarrel(0.45F, 0.0, 3.8365,-10.2)
                .setStock(1.0F, 0.0, 3.1294, 8.3)
                .setUnderBarrel(1.0F, 0.0, 2.63, -0.5)
                .build());


        this.addGun(new ResourceLocation(Reference.MOD_ID, "rifle_scout_kaiser"), Gun.Builder.create()
                .setFireRate(22)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(8)
                .setReloadAmount(1)
                .setRecoilAngle(10.0F)
                .setRecoilKick(0.5F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.R762.get())
                .setDamage(10.0F)
                .setProjectileAffectedByGravity(true)
                .setProjectileSize(0.0625F)
                .setProjectileSpeed(20.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_RIFLE_SCOUT_KAISER_FIRE.get())
                .setReloadSound(ModSounds.ITEM_RIFLE_SCOUT_KAISER_RELOAD.get())
                .setCockSound(ModSounds.ITEM_RIFLE_SCOUT_KAISER_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_RIFLE_SCOUT_KAISER_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_RIFLE_SCOUT_KAISER_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.8365, -10.21)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 4.6223, 6.0))
                .setScope(1.0F, 0.0, 4.3, 3.3)
                .setBarrel(0.45F, 0.0, 3.8365,-10.2)
                .setStock(1.0F, 0.0, 3.1294, 8.3)
                .setUnderBarrel(1.0F, 0.0, 2.63, -0.5)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "smg"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(4)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(30)
                .setReloadAmount(10)
                .setRecoilAngle(4.0F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.P45.get())
                .setDamage(6.0F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_SMG_FIRE.get())
                .setReloadSound(ModSounds.ITEM_SMG_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SMG_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SMG_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SMG_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.3, 2.64)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 4.5, -1.0))
                .setScope(0.75F, 0.0, 3.7, 6.0)
                .setBarrel(0.5F, 0.0, 3.3, 2.65)
                .setStock(1.0F, 0.0, 3.3, 7.95)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "smg_advanced"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(3)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(40)
                .setReloadAmount(20)
                .setRecoilAngle(4.0F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.P9.get())
                .setDamage(6.0F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_SMG_ADVANCED_FIRE.get())
                .setReloadSound(ModSounds.ITEM_SMG_ADVANCED_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SMG_ADVANCED_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SMG_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SMG_ADVANCED_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.3, 2.64)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 4.5, -1.0))
                .setScope(0.75F, 0.0, 3.7, 6.0)
                .setBarrel(0.5F, 0.0, 3.3, 2.65)
                .setStock(1.0F, 0.0, 3.3, 7.95)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "lmg"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(4)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(100)
                .setReloadAmount(25)
                .setRecoilAngle(4.0F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.R556.get())
                .setDamage(6.0F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_LMG_FIRE.get())
                .setReloadSound(ModSounds.ITEM_LMG_RELOAD.get())
                .setCockSound(ModSounds.ITEM_LMG_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_LMG_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_LMG_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.3, 2.64)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 4.5, -1.0))
                .setScope(0.75F, 0.0, 3.7, 6.0)
                .setBarrel(0.5F, 0.0, 3.3, 2.65)
                .setStock(1.0F, 0.0, 3.3, 7.95)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "lmg_gp"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(4)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(100)
                .setReloadAmount(25)
                .setRecoilAngle(4.0F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.R762.get())
                .setDamage(6.0F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_LMG_GP_FIRE.get())
                .setReloadSound(ModSounds.ITEM_LMG_GP_RELOAD.get())
                .setCockSound(ModSounds.ITEM_LMG_GP_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_LMG_GP_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_LMG_GP_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.3, 2.64)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 4.5, -1.0))
                .setScope(0.75F, 0.0, 3.7, 6.0)
                .setBarrel(0.5F, 0.0, 3.3, 2.65)
                .setStock(1.0F, 0.0, 3.3, 7.95)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "bazooka"), Gun.Builder.create()
                .setFireRate(80)
                .setGripType(GripType.BAZOOKA)
                .setMaxAmmo(1)
                .setRecoilAngle(10.0F)
                .setRecoilDurationOffset(0.25F)
                .setAmmo(ModItems.MISSILE.get())
                .setDamage(25.0F)
                .setProjectileVisible(true)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(2.0F)
                .setProjectileLife(150)
                .setFireSound(ModSounds.ITEM_BAZOOKA_FIRE.get())
                .setReloadSound(ModSounds.ITEM_PISTOL_RELOAD.get())
                .setMuzzleFlash(2.0, 0.0, 4.3, -8.01)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.5F)
                        .setOffset(3.5, 4.3, 16.0))
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "grenade_launcher"), Gun.Builder.create()
                .setFireRate(20)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(6)
                .setReloadAmount(1)
                .setRecoilAngle(5.0F)
                .setRecoilKick(1.0F)
                .setRecoilDurationOffset(0.25F)
                .setAmmo(ModItems.GRENADE.get())
                .setDamage(15.0F)
                .setProjectileVisible(true)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(1.5F)
                .setProjectileLife(50)
                .setProjectileAffectedByGravity(true)
                .setFireSound(ModSounds.ITEM_GRENADE_LAUNCHER_FIRE.get())
                .setReloadSound(ModSounds.ITEM_PISTOL_RELOAD.get())
                .setMuzzleFlash(0.75, 0.0, 3.5, -3.8)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 5.7, 3.0))
                .setScope(1.0F, 0.0, 5.2, 2.7)
                .setStock(1.0F, 0.0, 3.6, 8.2)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "sniper"), Gun.Builder.create()
                .setFireRate(40)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(5)
                .setReloadAmount(1)
                .setRecoilAngle(10.0F)
                .setRecoilKick(1.0F)
                .setRecoilDurationOffset(0.5F)
                .setRecoilAdsReduction(0.4F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.S50.get())
                .setDamage(18.0F)
                .setProjectileAffectedByGravity(true)
                .setProjectileSize(0.0625F)
                .setProjectileSpeed(25.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_SNIPER_FIRE.get())
                .setReloadSound(ModSounds.ITEM_SNIPER_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SNIPER_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SNIPER_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SNIPER_ENCHANTED_FIRE.get())
                .setMuzzleFlash(1.0, 0.0, 3.6, -9.41)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 5.1, 2.0))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6, -9.4)
                .setUnderBarrel(1.0F, 0.0, 3.0, -0.5)
                .build());


        this.addGun(new ResourceLocation(Reference.MOD_ID, "sniper_cheytac"), Gun.Builder.create()
                .setFireRate(20)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(7)
                .setReloadAmount(1)
                .setRecoilAngle(10.0F)
                .setRecoilKick(1.0F)
                .setRecoilDurationOffset(0.5F)
                .setRecoilAdsReduction(0.4F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.S50.get())
                .setDamage(18.0F)
                .setProjectileAffectedByGravity(true)
                .setProjectileSize(0.0625F)
                .setProjectileSpeed(25.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_SNIPER_CHEYTAC_FIRE.get())
                .setReloadSound(ModSounds.ITEM_SNIPER_CHEYTAC_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SNIPER_CHEYTAC_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SNIPER_CHEYTAC_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SNIPER_CHEYTAC_ENCHANTED_FIRE.get())
                .setMuzzleFlash(1.0, 0.0, 3.6, -9.41)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 5.1, 2.0))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6, -9.4)
                .setUnderBarrel(1.0F, 0.0, 3.0, -0.5)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "sniper_grenade"), Gun.Builder.create()
                .setFireRate(30)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(4)
                .setReloadAmount(1)
                .setRecoilAngle(10.0F)
                .setRecoilKick(1.0F)
                .setRecoilDurationOffset(0.5F)
                .setRecoilAdsReduction(0.4F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.X20.get())
                .setDamage(18.0F)
                .setProjectileAffectedByGravity(true)
                .setProjectileSize(0.0625F)
                .setProjectileSpeed(25.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_SNIPER_GRENADE_FIRE.get())
                .setReloadSound(ModSounds.ITEM_SNIPER_GRENADE_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SNIPER_GRENADE_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SNIPER_GRENADE_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SNIPER_GRENADE_ENCHANTED_FIRE.get())
                .setMuzzleFlash(1.0, 0.0, 3.6, -9.41)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 5.1, 2.0))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6, -9.4)
                .setUnderBarrel(1.0F, 0.0, 3.0, -0.5)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "mini_gun"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(2)
                .setGripType(GripType.MINI_GUN)
                .setMaxAmmo(100)
                .setReloadAmount(10)
                .setRecoilAngle(1.0F)
                .setAlwaysSpread(true)
                .setSpread(7.0F)
                .setAmmo(ModItems.R762.get())
                .setDamage(5.0F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(8.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_MINI_GUN_FIRE.get())
                .setReloadSound(ModSounds.ITEM_PISTOL_RELOAD.get())
                .setEnchantedFireSound(ModSounds.ITEM_MINI_GUN_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 2.7, -11.51)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "shotgun"), Gun.Builder.create()
                .setFireRate(20)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(8)
                .setReloadAmount(1)
                .setRecoilKick(0.5F)
                .setRecoilAngle(10.0F)
                .setRecoilAdsReduction(0.4F)
                .setProjectileAmount(5)
                .setAlwaysSpread(true)
                .setSpread(20.0F)
                .setAmmo(ModItems.G12.get())
                .setDamage(18.0F)
                .setProjectileSize(1.0F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(5)
                .setFireSound(ModSounds.ITEM_SHOTGUN_FIRE.get())
                .setReloadSound(ModSounds.ITEM_SHOTGUN_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SHOTGUN_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SHOTGUN_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SHOTGUN_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6505, -3.81)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 5.1, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6506, -3.8)
                .setStock(1.0F, 0.0, 3.6506, 8.4)
                .build());


        this.addGun(new ResourceLocation(Reference.MOD_ID, "shotgun_tactical"), Gun.Builder.create()
                .setFireRate(8)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(7)
                .setReloadAmount(1)
                .setRecoilKick(0.5F)
                .setRecoilAngle(10.0F)
                .setRecoilAdsReduction(0.4F)
                .setProjectileAmount(5)
                .setAlwaysSpread(true)
                .setSpread(20.0F)
                .setAmmo(ModItems.G12.get())
                .setDamage(18.0F)
                .setProjectileSize(1.0F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(5)
                .setFireSound(ModSounds.ITEM_SHOTGUN_TACTICAL_FIRE.get())
                .setReloadSound(ModSounds.ITEM_SHOTGUN_TACTICAL_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SHOTGUN_TACTICAL_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SHOTGUN_TACTICAL_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SHOTGUN_TACTICAL_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6505, -3.81)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 5.1, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6506, -3.8)
                .setStock(1.0F, 0.0, 3.6506, 8.4)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "shotgun_auto"), Gun.Builder.create()
                .setFireRate(5)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(12)
                .setReloadAmount(2)
                .setRecoilKick(0.5F)
                .setRecoilAngle(10.0F)
                .setRecoilAdsReduction(0.4F)
                .setProjectileAmount(5)
                .setAlwaysSpread(true)
                .setSpread(20.0F)
                .setAmmo(ModItems.G12.get())
                .setDamage(12.0F)
                .setProjectileSize(1.0F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(5)
                .setFireSound(ModSounds.ITEM_SHOTGUN_AUTO_FIRE.get())
                .setReloadSound(ModSounds.ITEM_SHOTGUN_AUTO_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SHOTGUN_AUTO_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SHOTGUN_AUTO_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SHOTGUN_AUTO_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6505, -3.81)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 5.1, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6506, -3.8)
                .setStock(1.0F, 0.0, 3.6506, 8.4)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "shotgun_db"), Gun.Builder.create()
                .setFireRate(8)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(2)
                .setReloadAmount(1)
                .setRecoilKick(0.5F)
                .setRecoilAngle(10.0F)
                .setRecoilAdsReduction(0.4F)
                .setProjectileAmount(5)
                .setAlwaysSpread(true)
                .setSpread(20.0F)
                .setAmmo(ModItems.G12.get())
                .setDamage(18.0F)
                .setProjectileSize(1.0F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(5)
                .setFireSound(ModSounds.ITEM_SHOTGUN_DB_FIRE.get())
                .setReloadSound(ModSounds.ITEM_SHOTGUN_DB_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SHOTGUN_DB_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SHOTGUN_DB_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SHOTGUN_DB_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6505, -3.81)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 5.1, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6506, -3.8)
                .setStock(1.0F, 0.0, 3.6506, 8.4)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "shotgun_qb"), Gun.Builder.create()
                .setFireRate(8)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(4)
                .setReloadAmount(1)
                .setRecoilKick(0.5F)
                .setRecoilAngle(10.0F)
                .setRecoilAdsReduction(0.4F)
                .setProjectileAmount(5)
                .setAlwaysSpread(true)
                .setSpread(20.0F)
                .setAmmo(ModItems.G12.get())
                .setDamage(18.0F)
                .setProjectileSize(1.0F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(5)
                .setFireSound(ModSounds.ITEM_SHOTGUN_QB_FIRE.get())
                .setReloadSound(ModSounds.ITEM_SHOTGUN_QB_FIRE.get())
                .setCockSound(ModSounds.ITEM_SHOTGUN_QB_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SHOTGUN_QB_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SHOTGUN_QB_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6505, -3.81)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 5.1, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6506, -3.8)
                .setStock(1.0F, 0.0, 3.6506, 8.4)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "becker"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(8)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(15)
                .setReloadAmount(1)
                .setRecoilKick(0.5F)
                .setRecoilAngle(10.0F)
                .setRecoilAdsReduction(0.4F)
                .setProjectileAmount(5)
                .setAlwaysSpread(true)
                .setSpread(20.0F)
                .setAmmo(ModItems.X20.get())
                .setDamage(18.0F)
                .setProjectileSize(1.0F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(5)
                .setFireSound(ModSounds.ITEM_BECKER_FIRE.get())
                .setReloadSound(ModSounds.ITEM_BECKER_RELOAD.get())
                .setCockSound(ModSounds.ITEM_BECKER_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_BECKER_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_BECKER_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6505, -3.81)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 5.1, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6506, -3.8)
                .setStock(1.0F, 0.0, 3.6506, 8.4)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "railgun"), Gun.Builder.create()
                .setFireRate(60)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(1)
                .setReloadAmount(1)
                .setRecoilKick(0.5F)
                .setRecoilAngle(10.0F)
                .setRecoilAdsReduction(0.4F)
                .setProjectileAmount(5)
                .setAlwaysSpread(true)
                .setSpread(20.0F)
                .setAmmo(ModItems.G12.get())
                .setDamage(18.0F)
                .setProjectileSize(1.0F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(5)
                .setFireSound(ModSounds.ITEM_RAILGUN_FIRE.get())
                .setReloadSound(ModSounds.ITEM_RAILGUN_RELOAD.get())
                .setCockSound(ModSounds.ITEM_RAILGUN_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_RAILGUN_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_RAILGUN_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6505, -3.81)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 5.1, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6506, -3.8)
                .setStock(1.0F, 0.0, 3.6506, 8.4)
                .build());
    }
}


